[밀켓마켓] Add : 상품 상세페이지
wecode-bootcamp-korea/21-1st-MealKatMarket-backend pull request #2
Opened 2021-06-10 12:37 UTC by pkc035

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 선택 시 상품 상세 정보 페이지 기능
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 상품 페이지는 회원, 비회원 모두 보여지는 페이지이기 때문에 token 데이터를 사용하지 않았습니다.
상품 상세 페이지는 상품에 대한 데이터들만 front에 보내면 되기에 심플하게 구현했는데 보완해야 할 부분이 있을까요 ?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-11 01:27 UTC, lordmyshepherd requested changes

2021-06-11 01:27 UTC, lordmyshepherd commented on products/views.py
> +
빈줄 지워주세요~

2021-06-11 01:27 UTC, lordmyshepherd commented on products/views.py
> +            #데이터베이스에 저장된 값이 혹시 5이상 일 경우 MAX 5로 설정
`if else`문을 사용하지 않는 방법이 없을까요?

데이터베이스에 5이상 저장되는 케이스가 있나요?

2021-06-11 01:27 UTC, lordmyshepherd commented on products/views.py
> +class FoodDetailView(View):
detail page에서 호출하기 때문에 detail 페이지의 food 정보를 호출한다고 생각할 수 있을 것 같아요.
데이터 기준으로 보면 Food 객체 하나를 받아오는 것이기 때문에, `FoodView`로 class명을 정하는게 좋을 것 같습니다.

```suggestion
class FoodlView(View):
```

2021-06-11 01:27 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message':'INVALID_KEY'}, status=400)
여기서 KeyError가 발생하는 상황이 있나요?

2021-06-11 01:27 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message':'NOT EXIST'}, status=400)
status `400`과 `404`의 차이를 찾아보면 좋을 것 같습니다.
차이점이 무엇인지 찾아보고 수정해주세요~

2021-06-11 03:54 UTC, pkc035 commented on products/views.py
> +            #데이터베이스에 저장된 값이 혹시 5이상 일 경우 MAX 5로 설정
이건 제가 테스트할때 랜덤 데이터를 넣었는데 star_score가 0.0~9.9 사이의 랜덤값이 들어가 있어서 임시로 넣어 놓은 부분입니다.

2021-06-11 03:54 UTC, pkc035 commented on products/views.py
> +class FoodDetailView(View):
FoodView로 수정하겠습니다.

2021-06-11 03:57 UTC, pkc035 commented on products/views.py
> +            return JsonResponse({'message':'INVALID_KEY'}, status=400)
혹시 몰라 front에서 key 값을 넣을 수도 있을까 생각해서 넣어봤는데 수정하겠습니다.

2021-06-11 03:59 UTC, pkc035 commented on products/views.py
> +            return JsonResponse({'message':'NOT EXIST'}, status=400)
400는 Bac Request, 404는 Not Found이기 때문에 404로 수정하겠습니다.

2021-06-11 04:00 UTC, pkc035 commented on products/views.py
> +
빈줄 수정했습니다.

2021-06-14 14:54 UTC, lordmyshepherd requested changes

2021-06-14 14:54 UTC, lordmyshepherd commented on products/views.py
> +            food             = Food.objects.get(id=food_id)
너무 많은 인덴트는 가독성을 안좋게 만듭니다.

```suggestion
            food = Food.objects.get(id=food_id)
```

2021-06-14 14:54 UTC, lordmyshepherd commented on products/views.py
> +                'image'            : [image.image_url for image in FoodImage.objects.filter(food=food_id)],
이미 위에서 food 객체를 가져온 상태입니다. `Food`와 `FoodImage`는 1:M관계 이므로 food에서 직접 food_image 리스트를 가져올 수 있습니다.
(힌트 `_set`)

```suggestion
                'image'            : [image.image_url for image in food.....],
```

2021-06-14 14:54 UTC, lordmyshepherd commented on products/views.py
> +            }
여기도 위에서 드린 피드백대로 `RequiredOption.objects.filter(food=food_id)`를 사용하지 않고 위에서 선언한 `food`객체를 통해서 필수옵션 리스트를 불러올 수 있습니다.

2021-06-14 14:54 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message':'MULITIPLE FOODS'}, status=400)
`Primary Key`로 조회하고 있기 때문에 `MultipleObjectsReturned` 에러가 발생할 상황은 없을 것 같습니다.

2021-06-16 02:49 UTC, closed without merging