[밀켓마켓] Add : 회원가입, 로그인 구현
wecode-bootcamp-korea/21-1st-MealKatMarket-backend pull request #3
Opened 2021-06-11 07:54 UTC by kimhyeji65

## 기타 질문 및 특이 사항
회원가입 로직이 너무 긴 것 같습니다. 
간단하게 줄 일 수 있는 방법이 있을 것 같은데 잘 모르겠습니다.

로그인 할 때 key 값이 이메일 , 비밀번호만 들어가게 하고 싶은데 휴대폰 번호, 이름이 들어가도 로그인이 됩니다. 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-11 09:10 UTC, lordmyshepherd requested changes

2021-06-11 09:10 UTC, lordmyshepherd commented on mealkatmarket/urls.py
> +
빈 줄은 지워주세요~

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'message': 'KEY_ERROR'}, status=400)
이미 line 56에서 KeyError가 발생하게 되면, `'message':'KEY_ERROR'`를 리턴하도록 되어 있네요~
중복되는 로직이므로 지워주셔도 될 것 같습니다~

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +            hashed_password    = bcrypt.hashpw(data['password'].encode('utf-8'),bcrypt.gensalt())
`complie + mathch`를 사용하는 것과 `match`만 사용하는 것의 차이점이 무엇인가요?

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +
빈 line 지워주세요~

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'token':acess_token}, status = 200)
반환해주는 token이 어떤 token인지 명확히 만들어주면 좋을 것 같아요!
나중에는 `access_token`이외에 다른 token도 많이 관리할 수 있기 때문이에요!

```suggestion
                return JsonResponse({'access_token' : acess_token}, status = 200)
```

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +            )
컨벤션만 맞춰주세요~
```suggestion
            User.objects.create(
                email        = data['email'],
                password     = hashed_password.decode('utf-8'), 
                name         = data['name'],
                phone_number = data['phone_number']
            )
```

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({"message":"중복된 비밀번호 입니다."}, status=401)
email에 password를 넣어주고 있는데 제대로 동작하는건가요?

```suggestion
            if User.objects.filter(email=data['password']):
                return JsonResponse({"message":"중복된 비밀번호 입니다."}, status=401)
```

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({"message":"중복된 비밀번호 입니다."}, status=401)
그리고 password는 중복될 수 있지 않을까요?

2021-06-11 09:10 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({"message":"중복된 이메일 입니다."}, status=401)
한국에서만 서비스하는게 아니라면, error 메세지는 영어로 만들어주시는게 좋습니다.

```suggestion
            if User.objects.filter(email=data['email']):
                return JsonResponse({"message":"DUPLICATED_EMAIL"}, status=401)
```

2021-06-11 10:02 UTC, kimhyeji65 commented on users/views.py
> +                return JsonResponse({'message': 'KEY_ERROR'}, status=400)
네 수정했습니다!

2021-06-14 06:23 UTC, lordmyshepherd requested changes

2021-06-14 06:23 UTC, lordmyshepherd commented on users/views.py
> +
line 8은 지워주세요~

2021-06-14 06:23 UTC, lordmyshepherd commented on users/views.py
> +            hashed_password    = bcrypt.hashpw(data['password'].encode('utf-8'),bcrypt.gensalt())
1. 정규식은 상수이므로 대문자로 작성해주세요~
```python
REGEX_USER_IDENTITY = '(^(?=.*[a-z])(?=.*\d)[a-z\d]{5,15}$)'
REGEX_PASSWORD      ='^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^~@$!%*#?&])[A-Za-z\d^~@$!#%*?&]{8,18}$'
REGEX_PHONE         = '^[0-9]{3}[0-9]{4}[0-9]{4}$'            
REGEX_NAME          = '^[가-힣]+'            
REGEX_EMAIL         = '(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'

```

2021-06-14 06:23 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'message':'SUCCESS'}, status = 201)
`201` 👍

2021-06-14 06:23 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({"message":"INVALID_PHONE_NUMBER"}, status=400)
line 26~33은 위로 빼는게 좋을 것 같네요! `User.objects.filter`는 db에 접근하기 때문에 최대한 마지막에 검증하는게 효율적일 것 같다는 생각입니다!

```python
if User.objects.filter(email=data['email']):                
   return JsonResponse({"message":"DUPLICATED_EMAIL"}, status=401)
```

2021-06-14 14:57 UTC, lordmyshepherd requested changes

2021-06-14 14:57 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'message':'INVALID_USER'}, status = 400)
여기서 User.DoesNotExist 에러가 발생할 수 있는 상황은 없을 것 같습니다.
왜 그럴까요?

2021-06-14 14:57 UTC, lordmyshepherd commented on users/views.py
> +
빈 줄 46번은 지워주세요~

2021-06-15 07:36 UTC, lordmyshepherd commented
LGTM 👍

2021-06-15 07:37 UTC, merged