[밀캣마켓] ADD: 상품 전체페이지 기능 구현
wecode-bootcamp-korea/21-1st-MealKatMarket-backend pull request #4
Opened 2021-06-11 09:10 UTC by castleq90

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- products의 전체상품을 뿌려주는 초기 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 데이터베이스에 저장된 전체 상품을 불러와서 상품 하나씩 정보를 전달하는 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 쿼리 파라미터를 사용한 request의 값을 어떻게 확인해 볼 수 있을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-06-11 09:18 UTC, lordmyshepherd requested changes

2021-06-11 09:18 UTC, lordmyshepherd commented on products/views.py
> +
여기 빈 줄은 지워주세요~

2021-06-11 09:18 UTC, lordmyshepherd commented on products/views.py
> +        foods = Food.objects.all()
만약에 Food 데이터가 500개라고 하면, 500개 전부 보내주는 건가요??
어떤 문제가 있을까요?

2021-06-13 10:54 UTC, castleq90 commented on products/views.py
> +
빈줄 지우기 완료했습니다 !

2021-06-13 11:01 UTC, castleq90 commented on products/views.py
> +        foods = Food.objects.all()
한번에 많은 정보를 뿌리는 거 자체가 데이터의 낭비인 것 같다고 생각해서
request에서 produts를 sorting할 수 있으면  좋을 것 같습니다.
쿼리 파라미터 방식으로 카테고리별 ListView 방식으로 구현 해보겠습니다.

2021-06-14 15:01 UTC, lordmyshepherd requested changes

2021-06-14 15:01 UTC, lordmyshepherd commented on products/views.py
> +        category_filter = request.GET.get('category')
명확하게 `id`를 붙여주는게 가독성을 높여줄 것 같네요!
```suggestion
        category_id = request.GET.get('category_id')
        # 또는
        category_id = request.GET.get('categoryId')
```

2021-06-14 15:01 UTC, lordmyshepherd commented on products/views.py
> +from .models import Category,CategoryFood,Food,FoodImage
line4와 line5 사이에 한 줄 띄워주세요~

2021-06-14 15:01 UTC, lordmyshepherd commented on products/views.py
> +            categoryfoods = category.categoryfood_set.all() # 카테고리에 묶여있는 중간테이블 전부를 표현
Q 객체를 사용하면, 더욱 유연하게 필터링 기능을 구현할 수 있을 것 같습니다.

Q객체를 사용해서 아래와 같이 구현해보고, 이에 맞춰서 line 16~29 code를 수정해보세요~

```python
q = Q()

if category_id:
    q = Q(categoryfood__category_id = category_id)

foods = Food.objects.filter(q)
```

2021-06-14 15:01 UTC, lordmyshepherd commented on products/views.py
> +# 4. 불러온 리스트를 별점 높은순, 후기 많은순으로 정렬하기
불필요한 주석 및 line은 삭제해주세요~

2021-06-15 04:19 UTC, castleq90 commented on products/views.py
> +        category_filter = request.GET.get('category')
category_id = request.GET.get('categoryId')로 변경완료 했습니다 !

2021-06-15 04:20 UTC, castleq90 commented on products/views.py
> +from .models import Category,CategoryFood,Food,FoodImage
import단과 class단을 나누어 한줄 띄웠습니다!

2021-06-15 04:24 UTC, castleq90 commented on products/views.py
> +# 4. 불러온 리스트를 별점 높은순, 후기 많은순으로 정렬하기
삭제하도록 하겠습니다 !

2021-06-16 02:33 UTC, castleq90 commented on products/views.py
> +            categoryfoods = category.categoryfood_set.all() # 카테고리에 묶여있는 중간테이블 전부를 표현
Q객체로 수정하여 완료했습니다 !

2021-06-16 02:50 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-06-16 02:50 UTC, lordmyshepherd commented on products/views.py
> +        sort        = request.GET.get('sort','id')
👍

2021-06-16 02:51 UTC, lordmyshepherd commented
컨플릭트 해결 해주세요!

2021-06-17 07:08 UTC, lordmyshepherd requested changes

2021-06-17 07:08 UTC, lordmyshepherd commented on products/views.py
> +        offset    = int(limit - page_size)
보통 offset limit은 아래와 같이 받아오도록 구현합니다.
페이지 number로 받아오는 케이스인 것 같네요. 이렇게 되면, 페이지에 종속적인 API가 되기 때문에, `offset`과 `limit`을 받아서 처리하는 방법으로 구현하는게 더 좋을 것 같습니다.

```python
    offset = int(request.GET.get('offset', 1))            
    limit  = int(request.GET.get('limit', 20))
```

2021-06-17 07:10 UTC, lordmyshepherd commented
**LGTM** 👍

2021-06-17 07:10 UTC, merged

2021-06-17 07:22 UTC, castleq90 commented on products/views.py
> +        offset    = int(limit - page_size)
프론트분들과 일정을 조율하여 수정이 가능하면 수정하도록 하겠습니다 !